baseURL: "https://www.avni.sh"
title: "avni.sh"
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
publishDir: "docs"
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Index
                  url: contents
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 15
                - name: Categories
                  url: categories/
                  weight: 25
                - name: Search
                  url: search/
                  weight: 30

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Hi, I'm Avnish. I am an Open Source Developer currently working at Red Hat. I write about Computer Science, Machine Learning, and Mathematics."
    author: "Avnish Pal"
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowFullTextinRSS: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: false
    images: ["avnish-cover.png"]

    profileMode:
        enabled: false
        title: Avnish Pal
        imageUrl: "https://avatars.githubusercontent.com/u/29746858?v=4"
        imageTitle: Profile
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Hi, I'm Avnish"
        Content: >

           - As an Open Source Developer working at Red Hat, I strive to share my knowledge on computer science, mathematics, and technology through articles. If you'd like to stay in the loop with the latest content from this blog, I invite you to subscribe to my <b><a target=_blank href="index.xml">RSS feed</a></b>. 
           
           - For a glimpse into my journey and the projects I've been involved in, feel free to check my <b><a target=_blank href="Resume-AvnishPal.pdf">resume</a></b>. 
           
          #  - I'm an Open Source Developer currently working at Red Hat.

          #  - I write about Self-Hosting, Homelab, and DevOps Technologies. 
        
          #  - <a target=_blank href="/subscribe">Subscribe</a> to my newsletter to stay up-to-date with latest articles published on this blog.
           
          #  - Download <a target=_blank href="Resume-AvnishPal-DevOps-2YoE.pdf">my resume</a> to learn about my projects and work experience.

    socialIcons:
        - name: cv
          url: "Resume-AvnishPal.pdf"
        - name: email
          url: "mailto:avnishnish07@gmail.com"
        - name: github
          url: "https://github.com/bovem"
        - name: medium
          url: "https://bovem.medium.com/"
        - name: ycombinator
          url: "https://news.ycombinator.com/user?id=bovem"
        - name: linkedin
          url: "http://www.linkedin.com/in/avnish-pal"
        # - name: stackoverflow
        #   url: "https://stackoverflow.com/users/15039093/avnish-pal"
        - name: rss
          url: "index.xml"

    # editPost:
    #     URL: "https://github.com/bovem/bovem.github.io/pulls"
    #     Text: "Suggest Changes" # edit text
        # appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "BOVEM"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        favicon: "/assets/favicon.ico"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
